server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/shopping_cart
    username: shopping_cart
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true