spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/warehouse
    username: warehouse
    password: 12345
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true