grpc:
  server:
    port: 9090
collector:
  kafka:
    producer:
      properties:
        "bootstrap-servers": localhost:9092
      topics:
        sensor-events: telemetry.sensors.v1
        hub-events: telemetry.hubs.v1