server:
  port: 8081

collector:
  kafka:
    consumer:
      properties:
        "group.id": aggregator
        "bootstrap-servers": localhost:9092
    producer:
      properties:
        bootstrap.servers: localhost:9092
    topics:
      sensor-events: telemetry.sensors.v1
      hub-events: telemetry.hubs.v1
      snapshot-events: telemetry.snapshots.v1