spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/analyzer
    username: analyzer
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

collector:
  kafka:
    properties:
      bootstrap-servers: localhost:9092
    hub:
      group-id: hub-analyzer
    snapshot:
        group-id: snapshot-analyzer
    consumer:
      properties:
        group-id: aggregator
    topics:
      sensor-events: telemetry.sensors.v1
      hub-events: telemetry.hubs.v1
      snapshot-events: telemetry.snapshots.v1

grpc:
  client:
    hub-router:
      address: static://localhost:59090
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext