server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/shopping_store
    username: shopping_store
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true