spring:
  datasource:
    url: jdbc:postgresql://localhost:8432/shopping_cart
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.http: TRACE
    org.slf4j: DEBUG
    ru.practicum: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      warehouse:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 60s